name: Format and build
on:
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
    - run: npm install
    - run: npm run prettier:check
    - run: npm run build
